# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-RemoteINC
version:      0.1
version_from: lib/Acme/RemoteINC.pm
installdirs:  site
requires:
    Net::FTP:                      0
    Test::Simple:                  0
    Tie::FTP:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
